language: python
python:
  - "2.7"
  - "3.3"
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy libatlas-dev liblapack-dev gfortran
    - sudo apt-get install -qq python-scipy python-matplotlib python-imaging
    - sudo apt-get install -qq python3-numpy python3-scipy
    - sudo apt-get install -qq libpng12-dev libtiff4-dev libwebp-dev
install:
  - "pip install imread"
  - "pip install nose"
  - "make debug"
script: nosetests
