sudo: required
dist: xenial
language: python
cache:
  ccache: true
  directories:
    - $HOME/.ccache
    - $HOME/miniconda

before_cache:
    - ccache --show-stats
    - ccache --zero-stats

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  global:
    - USE_CCACHE=1
  matrix:
    - NUMPY_VERSION=1.10
    - NUMPY_VERSION=1.11
    - NUMPY_VERSION=1.12
    - NUMPY_VERSION=1.13
    - NUMPY_VERSION=1.14
    - NUMPY_VERSION=1.15
    - NUMPY_VERSION=1.16
    - NUMPY_VERSION=1.17
    - NUMPY_VERSION=1.18


# Some combinations seem to be missing on conda
matrix:
  exclude:
    - python: "2.7"
      env: NUMPY_VERSION=1.17
    - python: "2.7"
      env: NUMPY_VERSION=1.18
    - python: "3.5"
      env: NUMPY_VERSION=1.16
    - python: "3.5"
      env: NUMPY_VERSION=1.17
    - python: "3.5"
      env: NUMPY_VERSION=1.18
    - python: "3.6"
      env: NUMPY_VERSION=1.10
    - python: "3.7"
      env: NUMPY_VERSION=1.10
    - python: "3.7"
      env: NUMPY_VERSION=1.12
    - python: "3.7"
      env: NUMPY_VERSION=1.13
before_install:
    - .travis/travis_before_install.sh
install:
    - export PATH=$HOME/miniconda/bin:$PATH
    - export PATH=/usr/lib/ccache:$PATH
    - .travis/travis_install.sh
script:
    - source activate condaenv
    - export DEBUG=2
    - coverage run --source=mahotas -m pytest -v
after_success:
    - source activate condaenv
    - coveralls

